name: Deploy Face Recognition App

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: aqiliman24/face-recognition
  IMAGE_TAG: latest
  INSTANCE_COUNT: 2  # Number of instances to deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: AI medkad server

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          docker logout

      - name: Copy docker-compose file to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/face-recognition"

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/face-recognition
            
            # Pull latest image
            docker pull --quiet ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            
            # Stop and remove existing containers
            docker compose down
            
            # Start new containers
            docker compose up -d
            
            # Verify deployment
            docker compose ps
            
            # Clean up unused images
            docker image prune -f
            
            # Reload Nginx to pick up changes
            sudo systemctl reload nginx
